agent:
  image: bugit/dre-agent:dev
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  skipBpf: true

collector:
  image: bugit/dre-collector:dev
  replicas: 1
  cluster: production

snapshot:
  encryptionSecret: dre-snapshot-key

s3:
  bucket: ""
