// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: api/proto/dre/v1/events.proto

package drev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IOEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PidTgid       uint64                 `protobuf:"varint,1,opt,name=pid_tgid,json=pidTgid,proto3" json:"pid_tgid,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,2,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Fd            uint32                 `protobuf:"varint,3,opt,name=fd,proto3" json:"fd,omitempty"`
	PayloadLen    uint32                 `protobuf:"varint,4,opt,name=payload_len,json=payloadLen,proto3" json:"payload_len,omitempty"`
	IsWrite       uint32                 `protobuf:"varint,5,opt,name=is_write,json=isWrite,proto3" json:"is_write,omitempty"`
	Comm          []byte                 `protobuf:"bytes,6,opt,name=comm,proto3" json:"comm,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	NodeId        string                 `protobuf:"bytes,8,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOEvent) Reset() {
	*x = IOEvent{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOEvent) ProtoMessage() {}

func (x *IOEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOEvent.ProtoReflect.Descriptor instead.
func (*IOEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *IOEvent) GetPidTgid() uint64 {
	if x != nil {
		return x.PidTgid
	}
	return 0
}

func (x *IOEvent) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *IOEvent) GetFd() uint32 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *IOEvent) GetPayloadLen() uint32 {
	if x != nil {
		return x.PayloadLen
	}
	return 0
}

func (x *IOEvent) GetIsWrite() uint32 {
	if x != nil {
		return x.IsWrite
	}
	return 0
}

func (x *IOEvent) GetComm() []byte {
	if x != nil {
		return x.Comm
	}
	return nil
}

func (x *IOEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IOEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *StreamEventsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TriggerSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotRequest) Reset() {
	*x = TriggerSnapshotRequest{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotRequest) ProtoMessage() {}

func (x *TriggerSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerSnapshotRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TriggerSnapshotRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type TriggerSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	StorageUri    string                 `protobuf:"bytes,3,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSnapshotResponse) Reset() {
	*x = TriggerSnapshotResponse{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSnapshotResponse) ProtoMessage() {}

func (x *TriggerSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TriggerSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *TriggerSnapshotResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TriggerSnapshotResponse) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *TriggerSnapshotResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type SnapshotInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CapturedAt    string                 `protobuf:"bytes,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`
	EventCount    int64                  `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	StorageUri    string                 `protobuf:"bytes,5,opt,name=storage_uri,json=storageUri,proto3" json:"storage_uri,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,6,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotInfo) Reset() {
	*x = SnapshotInfo{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotInfo) ProtoMessage() {}

func (x *SnapshotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotInfo.ProtoReflect.Descriptor instead.
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnapshotInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SnapshotInfo) GetCapturedAt() string {
	if x != nil {
		return x.CapturedAt
	}
	return ""
}

func (x *SnapshotInfo) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *SnapshotInfo) GetStorageUri() string {
	if x != nil {
		return x.StorageUri
	}
	return ""
}

func (x *SnapshotInfo) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*SnapshotInfo        `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dre_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dre_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *ListSnapshotsResponse) GetSnapshots() []*SnapshotInfo {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_api_proto_dre_v1_events_proto protoreflect.FileDescriptor

const file_api_proto_dre_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/dre/v1/events.proto\x12\x06dre.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xda\x01\n" +
	"\aIOEvent\x12\x19\n" +
	"\bpid_tgid\x18\x01 \x01(\x04R\apidTgid\x12!\n" +
	"\ftimestamp_ns\x18\x02 \x01(\x04R\vtimestampNs\x12\x0e\n" +
	"\x02fd\x18\x03 \x01(\rR\x02fd\x12\x1f\n" +
	"\vpayload_len\x18\x04 \x01(\rR\n" +
	"payloadLen\x12\x19\n" +
	"\bis_write\x18\x05 \x01(\rR\aisWrite\x12\x12\n" +
	"\x04comm\x18\x06 \x01(\fR\x04comm\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x17\n" +
	"\anode_id\x18\b \x01(\tR\x06nodeId\".\n" +
	"\x13StreamEventsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"H\n" +
	"\x16TriggerSnapshotRequest\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\x92\x01\n" +
	"\x17TriggerSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vstorage_uri\x18\x03 \x01(\tR\n" +
	"storageUri\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\"\xb8\x01\n" +
	"\fSnapshotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\tR\n" +
	"capturedAt\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\x03R\n" +
	"eventCount\x12\x1f\n" +
	"\vstorage_uri\x18\x05 \x01(\tR\n" +
	"storageUri\x12!\n" +
	"\fdownload_url\x18\x06 \x01(\tR\vdownloadUrl\"K\n" +
	"\x15ListSnapshotsResponse\x122\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x14.dre.v1.SnapshotInfoR\tsnapshots2O\n" +
	"\vEventIngest\x12@\n" +
	"\fStreamEvents\x12\x0f.dre.v1.IOEvent\x1a\x1b.dre.v1.StreamEventsRequest(\x010\x012\xac\x01\n" +
	"\x0eCollectorAdmin\x12R\n" +
	"\x0fTriggerSnapshot\x12\x1e.dre.v1.TriggerSnapshotRequest\x1a\x1f.dre.v1.TriggerSnapshotResponse\x12F\n" +
	"\rListSnapshots\x12\x16.google.protobuf.Empty\x1a\x1d.dre.v1.ListSnapshotsResponseB4Z2github.com/bugit/dre-engine/api/proto/dre/v1;drev1b\x06proto3"

var (
	file_api_proto_dre_v1_events_proto_rawDescOnce sync.Once
	file_api_proto_dre_v1_events_proto_rawDescData []byte
)

func file_api_proto_dre_v1_events_proto_rawDescGZIP() []byte {
	file_api_proto_dre_v1_events_proto_rawDescOnce.Do(func() {
		file_api_proto_dre_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dre_v1_events_proto_rawDesc), len(file_api_proto_dre_v1_events_proto_rawDesc)))
	})
	return file_api_proto_dre_v1_events_proto_rawDescData
}

var file_api_proto_dre_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_dre_v1_events_proto_goTypes = []any{
	(*IOEvent)(nil),                 // 0: dre.v1.IOEvent
	(*StreamEventsRequest)(nil),     // 1: dre.v1.StreamEventsRequest
	(*TriggerSnapshotRequest)(nil),  // 2: dre.v1.TriggerSnapshotRequest
	(*TriggerSnapshotResponse)(nil), // 3: dre.v1.TriggerSnapshotResponse
	(*SnapshotInfo)(nil),            // 4: dre.v1.SnapshotInfo
	(*ListSnapshotsResponse)(nil),   // 5: dre.v1.ListSnapshotsResponse
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_api_proto_dre_v1_events_proto_depIdxs = []int32{
	4, // 0: dre.v1.ListSnapshotsResponse.snapshots:type_name -> dre.v1.SnapshotInfo
	0, // 1: dre.v1.EventIngest.StreamEvents:input_type -> dre.v1.IOEvent
	2, // 2: dre.v1.CollectorAdmin.TriggerSnapshot:input_type -> dre.v1.TriggerSnapshotRequest
	6, // 3: dre.v1.CollectorAdmin.ListSnapshots:input_type -> google.protobuf.Empty
	1, // 4: dre.v1.EventIngest.StreamEvents:output_type -> dre.v1.StreamEventsRequest
	3, // 5: dre.v1.CollectorAdmin.TriggerSnapshot:output_type -> dre.v1.TriggerSnapshotResponse
	5, // 6: dre.v1.CollectorAdmin.ListSnapshots:output_type -> dre.v1.ListSnapshotsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_dre_v1_events_proto_init() }
func file_api_proto_dre_v1_events_proto_init() {
	if File_api_proto_dre_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dre_v1_events_proto_rawDesc), len(file_api_proto_dre_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_dre_v1_events_proto_goTypes,
		DependencyIndexes: file_api_proto_dre_v1_events_proto_depIdxs,
		MessageInfos:      file_api_proto_dre_v1_events_proto_msgTypes,
	}.Build()
	File_api_proto_dre_v1_events_proto = out.File
	file_api_proto_dre_v1_events_proto_goTypes = nil
	file_api_proto_dre_v1_events_proto_depIdxs = nil
}
