// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: api/proto/dre/v1/events.proto

package drev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngest_StreamEvents_FullMethodName = "/dre.v1.EventIngest/StreamEvents"
)

// EventIngestClient is the client API for EventIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngestClient interface {
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOEvent, StreamEventsRequest], error)
}

type eventIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestClient(cc grpc.ClientConnInterface) EventIngestClient {
	return &eventIngestClient{cc}
}

func (c *eventIngestClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOEvent, StreamEventsRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngest_ServiceDesc.Streams[0], EventIngest_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IOEvent, StreamEventsRequest]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngest_StreamEventsClient = grpc.BidiStreamingClient[IOEvent, StreamEventsRequest]

// EventIngestServer is the server API for EventIngest service.
// All implementations must embed UnimplementedEventIngestServer
// for forward compatibility.
type EventIngestServer interface {
	StreamEvents(grpc.BidiStreamingServer[IOEvent, StreamEventsRequest]) error
	mustEmbedUnimplementedEventIngestServer()
}

// UnimplementedEventIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestServer struct{}

func (UnimplementedEventIngestServer) StreamEvents(grpc.BidiStreamingServer[IOEvent, StreamEventsRequest]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventIngestServer) mustEmbedUnimplementedEventIngestServer() {}
func (UnimplementedEventIngestServer) testEmbeddedByValue()                     {}

// UnsafeEventIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestServer will
// result in compilation errors.
type UnsafeEventIngestServer interface {
	mustEmbedUnimplementedEventIngestServer()
}

func RegisterEventIngestServer(s grpc.ServiceRegistrar, srv EventIngestServer) {
	// If the following call panics, it indicates UnimplementedEventIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngest_ServiceDesc, srv)
}

func _EventIngest_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestServer).StreamEvents(&grpc.GenericServerStream[IOEvent, StreamEventsRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngest_StreamEventsServer = grpc.BidiStreamingServer[IOEvent, StreamEventsRequest]

// EventIngest_ServiceDesc is the grpc.ServiceDesc for EventIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dre.v1.EventIngest",
	HandlerType: (*EventIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventIngest_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/dre/v1/events.proto",
}

const (
	CollectorAdmin_TriggerSnapshot_FullMethodName = "/dre.v1.CollectorAdmin/TriggerSnapshot"
	CollectorAdmin_ListSnapshots_FullMethodName   = "/dre.v1.CollectorAdmin/ListSnapshots"
)

// CollectorAdminClient is the client API for CollectorAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorAdminClient interface {
	TriggerSnapshot(ctx context.Context, in *TriggerSnapshotRequest, opts ...grpc.CallOption) (*TriggerSnapshotResponse, error)
	ListSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
}

type collectorAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorAdminClient(cc grpc.ClientConnInterface) CollectorAdminClient {
	return &collectorAdminClient{cc}
}

func (c *collectorAdminClient) TriggerSnapshot(ctx context.Context, in *TriggerSnapshotRequest, opts ...grpc.CallOption) (*TriggerSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerSnapshotResponse)
	err := c.cc.Invoke(ctx, CollectorAdmin_TriggerSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorAdminClient) ListSnapshots(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, CollectorAdmin_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorAdminServer is the server API for CollectorAdmin service.
// All implementations must embed UnimplementedCollectorAdminServer
// for forward compatibility.
type CollectorAdminServer interface {
	TriggerSnapshot(context.Context, *TriggerSnapshotRequest) (*TriggerSnapshotResponse, error)
	ListSnapshots(context.Context, *emptypb.Empty) (*ListSnapshotsResponse, error)
	mustEmbedUnimplementedCollectorAdminServer()
}

// UnimplementedCollectorAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollectorAdminServer struct{}

func (UnimplementedCollectorAdminServer) TriggerSnapshot(context.Context, *TriggerSnapshotRequest) (*TriggerSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerSnapshot not implemented")
}
func (UnimplementedCollectorAdminServer) ListSnapshots(context.Context, *emptypb.Empty) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedCollectorAdminServer) mustEmbedUnimplementedCollectorAdminServer() {}
func (UnimplementedCollectorAdminServer) testEmbeddedByValue()                        {}

// UnsafeCollectorAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorAdminServer will
// result in compilation errors.
type UnsafeCollectorAdminServer interface {
	mustEmbedUnimplementedCollectorAdminServer()
}

func RegisterCollectorAdminServer(s grpc.ServiceRegistrar, srv CollectorAdminServer) {
	// If the following call panics, it indicates UnimplementedCollectorAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollectorAdmin_ServiceDesc, srv)
}

func _CollectorAdmin_TriggerSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorAdminServer).TriggerSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorAdmin_TriggerSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorAdminServer).TriggerSnapshot(ctx, req.(*TriggerSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectorAdmin_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorAdminServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollectorAdmin_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorAdminServer).ListSnapshots(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectorAdmin_ServiceDesc is the grpc.ServiceDesc for CollectorAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dre.v1.CollectorAdmin",
	HandlerType: (*CollectorAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerSnapshot",
			Handler:    _CollectorAdmin_TriggerSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _CollectorAdmin_ListSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/dre/v1/events.proto",
}
