apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snapshot.encryptionSecret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  key: {{ .Values.snapshot.encryptionKey | quote }}
